int main() {
    int i, j;
    i = malloc(SIZE*3);
    j = 1;
    i[0] = 5; i[1] = 7; i[2] = 3;

    printf("ADD\n");
    j += 1;         printf("%d ?= 2\n", j);
    i[0] += 1;      printf("%d ?= 6\n", i[0]);
    *i += 1;        printf("%d ?= 7\n", *i);
    printf("\nMUL\n");
    j *= 2;         printf("%d ?= 4\n", j);
    i[0] *= 2;      printf("%d ?= 14\n", i[0]);
    *i *= 2;        printf("%d ?= 28\n", *i);
    printf("\nSUB\n");
    j -= -15;       printf("%d ?= 19\n", j);
    i[0] -= 1;      printf("%d ?= 27\n", i[0]);
    *i -= 2;        printf("%d ?= 25\n", *i);
    printf("\nDIV\n");
    j /= 2;         printf("%d ?= 9\n", j);
    i[0] /= 5;      printf("%d ?= 5\n", i[0]);
    *i /= 2;        printf("%d ?= 2\n", *i);
    printf("\nMOD\n");
    j = 5;
    j %= 3;         printf("%d ?= 2\n", j);
    i[0] = 10;
    i[0] %= 4;      printf("%d ?= 2\n", i[0]);
    *i = 15;
    *i %= 6;        printf("%d ?= 3\n", *i);
    printf("\nSHL\n");
    j <<= 2;        printf("%d ?= 8\n", j);
    i[0] <<= 1;     printf("%d ?= 6\n", i[0]);
    *i <<= 2;       printf("%d ?= 24\n", *i);
    printf("\nSHR\n");
    j >>= 1;        printf("%d ?= 4\n", j);
    i[0] >>= 1;     printf("%d ?= 12\n", i[0]);
    *i >>= 1;       printf("%d ?= 6\n", *i);
    printf("\nOR\n");
    j |= 1;         printf("%d ?= 5\n", j);
    i[0] |= 5;      printf("%d ?= 7\n", i[0]);
    *i |= 9;        printf("%d ?= 15\n", *i);
    printf("\nAND\n");
    j &= 3;         printf("%d ?= 1\n", j);
    i[0] &= 11;     printf("%d ?= 11\n", i[0]);
    *i &= 7;        printf("%d ?= 3\n", *i);
    printf("\nXOR\n");
    j ^= 5;         printf("%d ?= 4\n", j);
    i[0] ^= 6;      printf("%d ?= 5\n", i[0]);
    *i ^= 6;        printf("%d ?= 3\n", *i);
}
