def expect(*args):
    res = ""
    res += "ADD\n"
    res += "2 ?= 2\n"
    res += "6 ?= 6\n"
    res += "7 ?= 7\n"
    res += "\nMUL\n"
    res += "4 ?= 4\n"
    res += "14 ?= 14\n"
    res += "28 ?= 28\n"
    res += "\nSUB\n"
    res += "19 ?= 19\n"
    res += "27 ?= 27\n"
    res += "25 ?= 25\n"
    res += "\nDIV\n"
    res += "9 ?= 9\n"
    res += "5 ?= 5\n"
    res += "2 ?= 2\n"
    res += "\nMOD\n"
    res += "2 ?= 2\n"
    res += "2 ?= 2\n"
    res += "3 ?= 3\n"
    res += "\nSHL\n"
    res += "8 ?= 8\n"
    res += "6 ?= 6\n"
    res += "24 ?= 24\n"
    res += "\nSHR\n"
    res += "4 ?= 4\n"
    res += "12 ?= 12\n"
    res += "6 ?= 6\n"
    res += "\nOR\n"
    res += "5 ?= 5\n"
    res += "7 ?= 7\n"
    res += "15 ?= 15\n"
    res += "\nAND\n"
    res += "1 ?= 1\n"
    res += "11 ?= 11\n"
    res += "3 ?= 3\n"
    res += "\nXOR\n"
    res += "4 ?= 4\n"
    res += "5 ?= 5\n"
    res += "3 ?= 3\n"
    return (0, res, "")

data = [
    [],
]
